language: node_js
node_js: node
before_script:
  - npm install -g gulp-cli
script: 
  - export NODE_ENV=production
  - gulp

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: solved-by-flexbox
  on:
    branch: zh
